public class HSU_SimpleCalculator {
    
    public static Integer add(Integer a, Integer b) {
        return a + b;
    }
    
    public static Integer subtract(Integer a, Integer b) {
        return a - b;
    }
    
    public static Integer multiply(Integer a, Integer b) {
        return a * b;
    }
    
    public static String getWelcomeMessage() {
        return 'Bienvenido a la calculadora simple';
    }
}